version: '3.8'

services:
  localstack:
    image: localstack/localstack:1.3.1
    environment:
      - EDGE_PORT=4566
      # https://docs.localstack.cloud/localstack/lambda-executors/
      # https://docs.localstack.cloud/localstack/configuration/#lambda
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      # for accessing karate mocks
      - LAMBDA_DOCKER_FLAGS=--add-host ingress.local:host-gateway
      - EAGER_SERVICE_LOADING=0
      - DEBUG=0
    ports:
      # https://docs.localstack.cloud/localstack/external-ports/
      - '4510-4559:4510-4559'
      # edge port
      - '4566:4566'
    volumes:
      - './.localstack:/var/lib/localstack'
      - './.docker-compose/localstack/etc/localstack/init/ready.d:/etc/localstack/init/ready.d'
      # for docker lambda executor
      - /var/run/docker.sock:/var/run/docker.sock
