[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Shawn Lim"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
lancedb = "^0.1.9"
boto3 = "^1.28.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
